made instructions more clear
whats-this/owo.sh pull request #6
Opened 2016-12-21 14:42 UTC by jaacks

2016-12-21 14:44 UTC, aurieh commented
👀

2016-12-21 14:44 UTC, jaacks commented
👀

2016-12-21 14:49 UTC, jakeoid commented
```
+5. Run `./script.sh`
+6. Put your token inside of `conf.cfg`, in `userkey="YOURUSERKEY"`
```

Makes no sense to run the script if there isn't a token, perhaps fix this?

2016-12-21 15:11 UTC, jakeoid requested changes
Needs to fix points 5. and 6. around.

2016-12-21 15:54 UTC, OkashiOdayakana commented on README.md
> +3. Run `sudo ./setup.sh`
It shouldn't be getting ran with sudo

2016-12-21 15:56 UTC, islacantwin requested changes
What @jakeoid said, and it should say to run anything as sudo.

2016-12-22 13:11 UTC, jakeoid commented
No response in over 22 hours, doesn't seem to want to fix the changes on his own.

/closed

2016-12-22 13:11 UTC, closed without merging